stages:
  import_data:
    cmd: python3 src/data/import_data.py
    deps:
    - src/data/import_data.py
    outs:
    - data/raw_data/raw.csv
  split_data:
    cmd: python3 src/data/split_data.py
    deps:
    - data/raw_data/raw.csv
    - src/data/split_data.py
    outs:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - data/processed_data/y_test.csv
    - data/processed_data/y_train.csv
  normalize_data:
    cmd: python3 src/data/normalize_data.py
    deps:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - src/data/normalize_data.py
    outs:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/X_train_scaled.csv
    - models/data/scaler.pkl
  gridsearch:
    cmd: python3 src/models/gridsearch.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - src/models/gridsearch.py
    outs:
    - models/data/best_params.pkl
  train_model:
    cmd: python3 src/models/train_model.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - models/data/best_params.pkl
    - src/models/train_model.py
    outs:
    - models/models/model.pkl
  evaluate_model:
    cmd: python3 src/models/evaluate_model.py
    deps:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/y_test.csv
    - models/models/model.pkl
    - src/models/evaluate_model.py
    outs:
    - data/processed_data/predictions.csv
    - metrics/scores.json
